@extends('layouts.app')
@section('title','Resume & Career AI - Admin')
@section('content')
<div class="page-header"><div><h1>Resume & Career AI</h1><p>Configure providers securely. API keys are encrypted and never exposed to participants.</p></div></div>
<div class="eh-tabs" data-eh-tabs><div class="eh-tab-nav"><button class="eh-tab-button active" data-eh-tab="config">Configuration</button><button class="eh-tab-button" data-eh-tab="usage">Usage</button></div>
<div class="eh-tab-content"><section class="eh-tab-pane active" data-eh-pane="config"><div class="eh-tab-section">
<form method="POST" action="{{ route('admin.career-ai.update') }}">@csrf @method('PUT')
<div class="form-grid"><div class="form-group"><label>Feature</label><select name="feature"><option value="career_ai">Career AI fallback</option><option value="resume_parsing">Resume Parsing</option><option value="resume_improvement">Resume Improvement</option><option value="ats_review">ATS Review</option><option value="job_tailoring">Job Tailoring</option><option value="cover_letter_generation">Cover Letter Generation</option></select></div><div class="form-group"><label>Provider</label><select name="provider"><option value="openai">OpenAI</option><option value="gemini">Gemini</option><option value="compatible">OpenAI-compatible</option></select></div><div class="form-group"><label>Model</label><input name="model" placeholder="e.g. gpt-5.6"></div><div class="form-group"><label>Endpoint</label><input name="endpoint" placeholder="Optional custom endpoint"></div><div class="form-group"><label>API key</label><input type="password" name="api_key" autocomplete="new-password" placeholder="Leave blank to keep existing key"></div><div class="form-group"><label>Participant daily limit</label><input type="number" name="user_daily_limit" value="20"></div></div>
<label><input type="checkbox" name="enabled" value="1"> Enable feature</label><br><br><button class="btn btn-primary">Save Configuration</button></form></div></section>
<section class="eh-tab-pane" data-eh-pane="usage"><div class="eh-tab-section"><div class="eh-data-list">@forelse($usage as $log)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-chart-line"></i></span><div class="eh-data-row-copy"><strong>{{ $log->feature }}</strong><span>{{ $log->provider }} · {{ $log->model }} · {{ $log->status }} · {{ $log->created_at }}</span></div></div></div>@empty<p>No AI usage yet.</p>@endforelse</div>{{ $usage->links() }}</div></section></div></div>
@endsection
