@extends('layouts.app')
@section('title','Dashboard - ElevateHer360')
@section('content')
<div class="page-header"><div><span class="eh-kicker">Participant Dashboard</span><h1>Welcome, {{ auth()->user()->profile?->given_name ?? auth()->user()->name }}</h1><p>Continue your learning, mentorship, career and opportunity journey.</p></div><div class="page-actions">@if(Route::has('profile.edit'))<a href="{{ route('profile.edit') }}" class="btn btn-outline"><i class="fas fa-user-pen"></i> Profile</a>@endif @if(Route::has('notifications.index'))<a href="{{ route('notifications.index') }}" class="btn btn-primary"><i class="fas fa-bell"></i> Notifications</a>@endif</div></div>
<div class="eh-stats"><div class="eh-stat"><span class="eh-stat-label">Learning</span><strong class="eh-stat-value">{{ isset($enrolments) ? $enrolments->count() : 0 }}</strong></div><div class="eh-stat"><span class="eh-stat-label">Mentorship</span><strong class="eh-stat-value">{{ !empty($mentorMatch) ? 1 : 0 }}</strong></div><div class="eh-stat"><span class="eh-stat-label">Applications</span><strong class="eh-stat-value">{{ isset($jobApplications) ? $jobApplications->count() : 0 }}</strong></div><div class="eh-stat"><span class="eh-stat-label">Resumes</span><strong class="eh-stat-value">{{ isset($resumes) ? $resumes->count() : 0 }}</strong></div></div>
<div class="eh-tabs" data-eh-tabs><div class="eh-tab-nav"><button class="eh-tab-button active" data-eh-tab="overview"><i class="fas fa-house"></i> Overview</button><button class="eh-tab-button" data-eh-tab="learning"><i class="fas fa-graduation-cap"></i> Learning</button><button class="eh-tab-button" data-eh-tab="mentorship"><i class="fas fa-user-group"></i> Mentorship</button><button class="eh-tab-button" data-eh-tab="career"><i class="fas fa-file-lines"></i> Career</button><button class="eh-tab-button" data-eh-tab="opportunities"><i class="fas fa-briefcase"></i> Opportunities</button><button class="eh-tab-button" data-eh-tab="calendar"><i class="fas fa-calendar-days"></i> Calendar</button></div><div class="eh-tab-content">
<section class="eh-tab-pane active" data-eh-pane="overview"><div class="eh-tab-section"><div class="eh-data-list">@if(Route::has('learning.my-courses'))<a class="eh-data-row" href="{{ route('learning.my-courses') }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-graduation-cap"></i></span><div class="eh-data-row-copy"><strong>Learning</strong><span>Continue your courses and track progress.</span></div></div><i class="fas fa-chevron-right"></i></a>@endif @if(Route::has('mentorship.dashboard'))<a class="eh-data-row" href="{{ route('mentorship.dashboard') }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-user-group"></i></span><div class="eh-data-row-copy"><strong>Mentorship</strong><span>Review mentor relationships, sessions and goals.</span></div></div><i class="fas fa-chevron-right"></i></a>@endif @if(Route::has('jobs.index'))<a class="eh-data-row" href="{{ route('jobs.index') }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-briefcase"></i></span><div class="eh-data-row-copy"><strong>Jobs</strong><span>Browse career opportunities and applications.</span></div></div><i class="fas fa-chevron-right"></i></a>@endif @if(Route::has('library.index'))<a class="eh-data-row" href="{{ route('library.index') }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-book-open"></i></span><div class="eh-data-row-copy"><strong>Library</strong><span>Access digital learning and career resources.</span></div></div><i class="fas fa-chevron-right"></i></a>@endif</div></div></section>
<section class="eh-tab-pane" data-eh-pane="learning"><div class="eh-tab-section"><div class="eh-data-list">@forelse($enrolments ?? [] as $enrolment)<a class="eh-data-row" href="{{ route('learning.course.show',$enrolment->course) }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-book"></i></span><div class="eh-data-row-copy"><strong>{{ $enrolment->course?->title }}</strong><span>{{ $enrolment->progress_percent ?? 0 }}% complete</span></div></div><i class="fas fa-chevron-right"></i></a>@empty<div class="eh-empty"><i class="fas fa-graduation-cap"></i><h3>No recent courses</h3><p>Your recent learning activity will appear here.</p></div>@endforelse</div></div></section>
<section class="eh-tab-pane" data-eh-pane="mentorship"><div class="eh-tab-section">@if(!empty($mentorMatch))<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-user-tie"></i></span><div class="eh-data-row-copy"><strong>Mentor connection</strong><span>Status: {{ $mentorMatch->status ?? 'Active' }}</span></div></div></div>@else<div class="eh-empty"><i class="fas fa-user-group"></i><h3>No active mentor match</h3><p>Your mentorship connection will appear here when available.</p></div>@endif</div></section>
<section class="eh-tab-pane" data-eh-pane="career"><div class="eh-tab-section"><div class="eh-data-list">@forelse($resumes ?? [] as $resume)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-file-lines"></i></span><div class="eh-data-row-copy"><strong>{{ $resume->title }}</strong><span>{{ $resume->is_default ? 'Default resume' : 'Resume' }}</span></div></div></div>@empty<div class="eh-empty"><i class="fas fa-file-lines"></i><h3>No resume yet</h3><p>Create your professional resume from the career section.</p>@if(Route::has('career.resume.index'))<a class="btn btn-primary" href="{{ route('career.resume.index') }}">Resume Builder</a>@endif</div>@endforelse</div></div></section>
<section class="eh-tab-pane" data-eh-pane="opportunities"><div class="eh-tab-section"><div class="eh-data-list">@forelse($jobApplications ?? [] as $application)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-paper-plane"></i></span><div class="eh-data-row-copy"><strong>{{ $application->job?->title }}</strong><span>{{ $application->job?->employer?->company_name }} · {{ ucfirst($application->status) }}</span></div></div></div>@empty<div class="eh-empty"><i class="fas fa-briefcase"></i><h3>No recent applications</h3><p>Explore opportunities and start applying.</p>@if(Route::has('jobs.index'))<a class="btn btn-primary" href="{{ route('jobs.index') }}">Browse Jobs</a>@endif</div>@endforelse</div></div></section>
<section class="eh-tab-pane" data-eh-pane="calendar"><div class="eh-tab-section"><div class="eh-data-list">@forelse($calendarEvents ?? [] as $event)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-calendar-check"></i></span><div class="eh-data-row-copy"><strong>{{ $event->title }}</strong><span>{{ $event->starts_at?->format('d M Y H:i') }}</span></div></div></div>@empty<div class="eh-empty"><i class="fas fa-calendar"></i><h3>No upcoming events</h3><p>Your upcoming activities will appear here.</p></div>@endforelse</div></div></section>
</div></div>
@endsection
