@extends('layouts.admin')
@section('title','Projects | ElevateHer360 Administration')
@section('content')
<div class="admin-page-header"><div><span class="admin-eyebrow">Programme Management</span><h1>Projects</h1><p>Manage projects linked to programmes.</p></div><div class="admin-page-actions"><button type="button" class="btn btn-primary" data-modal-open="projectCreate"><i class="fas fa-plus"></i> Add Project</button></div></div>
@include('admin.shared.feedback')
<div class="admin-stats-grid compact">@foreach([['total','Total Projects','fa-diagram-project'],['active','Active','fa-circle-check'],['draft','Draft','fa-pen'],['completed','Completed','fa-flag-checkered']] as [$k,$l,$i])<div class="admin-stat"><span class="admin-stat-icon"><i class="fas {{ $i }}"></i></span><div><small>{{ $l }}</small><strong>{{ number_format($stats[$k]??0) }}</strong></div></div>@endforeach</div>
<div class="admin-panel"><form method="GET" class="admin-toolbar"><div class="search-box"><i class="fas fa-magnifying-glass"></i><input name="search" value="{{ request('search') }}" placeholder="Search project name, code or description..."></div><select name="programme_id"><option value="">All programmes</option>@foreach($programmes as $p)<option value="{{ $p->id }}" @selected((string)request('programme_id')===(string)$p->id)>{{ $p->name }}</option>@endforeach</select><select name="status"><option value="">All statuses</option>@foreach(['draft','active','completed','on_hold','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst(str_replace('_',' ',$s)) }}</option>@endforeach</select><select name="per_page">@foreach([10,20,25,50,100] as $n)<option value="{{ $n }}" @selected((int)request('per_page',20)===$n)>{{ $n }}/page</option>@endforeach</select><button class="btn btn-primary btn-sm">Apply</button><a href="{{ route('admin.projects.index') }}" class="btn btn-outline btn-sm">Reset</a></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Project</th><th>Programme</th><th>Dates</th><th>Status</th><th class="table-actions">Actions</th></tr></thead><tbody>@forelse($projects as $project)<tr><td><strong>{{ $project->name }}</strong><small class="admin-cell-hint">{{ $project->code ?: 'No code' }}</small></td><td>{{ $project->programme?->name ?: '—' }}</td><td>{{ optional($project->start_date)->format('d M Y') ?: '—' }} — {{ optional($project->end_date)->format('d M Y') ?: '—' }}</td><td><span class="status-chip {{ $project->status }}">{{ ucfirst(str_replace('_',' ',$project->status)) }}</span></td><td class="table-actions"><div class="action-group"><button class="btn-icon" type="button" data-modal-open="project{{ $project->id }}"><i class="fas fa-pen"></i></button><button class="btn-icon danger" type="button" data-modal-open="projectDelete{{ $project->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="5"><div class="admin-empty">No projects found.</div></td></tr>@endforelse</tbody></table></div><div class="admin-pagination">{{ $projects->links() }}</div></div>

@php($blank=new \App\Models\Project())
@include('admin.projects.modal',['id'=>'projectCreate','title'=>'Add Project','project'=>$blank,'action'=>route('admin.projects.store'),'method'=>'POST'])
@foreach($projects as $project)
@include('admin.projects.modal',['id'=>'project'.$project->id,'title'=>'Edit Project','project'=>$project,'action'=>route('admin.projects.update',$project),'method'=>'PUT'])
<div class="eh-modal" id="projectDelete{{ $project->id }}" aria-hidden="true"><div class="eh-modal-dialog eh-modal-sm"><div class="eh-modal-header"><div><h2>Delete Project?</h2><p>{{ $project->name }}</p></div><button type="button" class="eh-modal-close" data-modal-close><i class="fas fa-xmark"></i></button></div><div class="eh-modal-body"><p>Delete only when no dependent records use this project.</p></div><div class="eh-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Cancel</button><form method="POST" action="{{ route('admin.projects.destroy',$project) }}">@csrf @method('DELETE')<button class="btn btn-danger">Delete</button></form></div></div></div>
@endforeach
@endsection
