@extends('layouts.app')
@section('title','Mentorship - ElevateHer360')
@section('content')
<div class="page-header"><div><span class="eh-kicker">Mentorship</span><h1>My Mentorship</h1><p>Manage mentor relationships, mentees, sessions and development goals.</p></div>@if(Route::has('mentorship.mentor-profile.edit'))<a href="{{ route('mentorship.mentor-profile.edit') }}" class="btn btn-outline"><i class="fas fa-user-pen"></i> Mentor Profile</a>@endif</div>
<div class="eh-stats"><div class="eh-stat"><span class="eh-stat-label">My Mentors</span><strong class="eh-stat-value">{{ $menteeMatches->count() }}</strong></div><div class="eh-stat"><span class="eh-stat-label">My Mentees</span><strong class="eh-stat-value">{{ $mentorMatches->count() }}</strong></div></div>
<div class="eh-tabs" data-eh-tabs><div class="eh-tab-nav" role="tablist"><button class="eh-tab-button active" data-eh-tab="overview"><i class="fas fa-house"></i> Overview</button><button class="eh-tab-button" data-eh-tab="mentors"><i class="fas fa-user-tie"></i> My Mentors</button><button class="eh-tab-button" data-eh-tab="mentees"><i class="fas fa-users"></i> My Mentees</button></div><div class="eh-tab-content">
<section class="eh-tab-pane active" data-eh-pane="overview"><div class="eh-tab-section"><div class="eh-tab-section-header"><div><h2>Mentorship Overview</h2><p>Your active mentorship relationships in one place.</p></div></div><div class="eh-data-list">@foreach($menteeMatches as $match)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-user-tie"></i></span><div class="eh-data-row-copy"><strong>{{ $match->mentor->name }}</strong><span>Mentor relationship</span></div></div><span class="eh-status">{{ $match->status }}</span></div>@endforeach @foreach($mentorMatches as $match)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-user-graduate"></i></span><div class="eh-data-row-copy"><strong>{{ $match->mentee->name }}</strong><span>Mentee relationship</span></div></div><span class="eh-status">{{ $match->status }}</span></div>@endforeach @if(!$mentorMatches->count() && !$menteeMatches->count())<div class="eh-empty"><i class="fas fa-user-group"></i><h3>No mentorship match yet</h3><p>Your mentorship connections will appear here once matched.</p></div>@endif</div></div></section>
<section class="eh-tab-pane" data-eh-pane="mentors"><div class="eh-tab-section"><div class="eh-data-list">@forelse($menteeMatches as $match)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-user-tie"></i></span><div class="eh-data-row-copy"><strong>{{ $match->mentor->name }}</strong><span>{{ ucfirst($match->status) }}</span></div></div></div>@empty<div class="eh-empty"><p>No mentor relationship yet.</p></div>@endforelse</div></div></section>
<section class="eh-tab-pane" data-eh-pane="mentees"><div class="eh-tab-section"><div class="eh-data-list">@forelse($mentorMatches as $match)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-user-graduate"></i></span><div class="eh-data-row-copy"><strong>{{ $match->mentee->name }}</strong><span>{{ ucfirst($match->status) }}</span></div></div></div>@empty<div class="eh-empty"><p>No mentees assigned yet.</p></div>@endforelse</div></div></section>
</div></div>
@endsection
