<?php
namespace App\Http\Controllers\HR;
use App\Http\Controllers\Controller;use App\Models\Appraisal;use App\Models\AppraisalKra;use App\Models\AppraisalKpi;use App\Models\AppraisalMeeting;use App\Models\Employee;use App\Services\HR\AppraisalScoreService;use App\Services\HR\AppraisalWorkflowService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class AppraisalWorkspaceController extends Controller {
 public function index(){ $e=Employee::where('user_id',auth()->id())->first();$mine=$e?Appraisal::with(['cycle','manager'])->where('employee_id',$e->id)->latest()->get():collect();$team=Appraisal::with(['cycle','employee.user'])->where('manager_user_id',auth()->id())->latest()->get();return view('hr.appraisals.workspace',compact('mine','team'));}
 public function show(Appraisal $a,AppraisalScoreService $s){$this->authorise($a);$a=$s->refresh($a);$a->load(['employee.user','manager','cycle','kras.kpis','meeting','statusHistory']);return view('hr.appraisals.workflow',['appraisal'=>$a]);}
 public function saveEmployee(Request $r,Appraisal $a,AppraisalScoreService $s,AppraisalWorkflowService $w){abort_unless($this->employee($a),403);abort_if($a->locked_at,422,'Appraisal is locked.');$d=$r->validate(['achievements'=>'nullable|string|max:30000','challenges'=>'nullable|string|max:30000','support_required'=>'nullable|string|max:30000','learning_completed'=>'nullable|string|max:30000','development_needs'=>'nullable|string|max:30000','employee_comments'=>'nullable|string|max:30000','kras'=>'nullable|array','kras.*.title'=>'required|string|max:255','kras.*.weight'=>'required|numeric|min:0|max:100','kras.*.expected_result'=>'nullable|string','kras.*.actual_result'=>'nullable|string','kras.*.employee_rating'=>'nullable|numeric|min:1|max:5','kras.*.kpis'=>'nullable|array','kras.*.kpis.*.title'=>'required|string|max:255','kras.*.kpis.*.target'=>'nullable|string|max:500','kras.*.kpis.*.actual_achievement'=>'nullable|string|max:500','kras.*.kpis.*.weight'=>'required|numeric|min:0|max:100','kras.*.kpis.*.employee_score'=>'nullable|numeric|min:1|max:5']);DB::transaction(function()use($a,$d){$a->update(collect($d)->only(['achievements','challenges','support_required','learning_completed','development_needs','employee_comments'])->all());$a->kras()->delete();foreach(($d['kras']??[]) as $i=>$kd){$kp=$kd['kpis']??[];unset($kd['kpis']);$kd['position']=$i;$kra=$a->kras()->create($kd);foreach($kp as $j=>$x){$x['position']=$j;$kra->kpis()->create($x);}}});if(in_array($a->status,['draft','returned_for_revision','goal_setting','self_assessment'],true))$w->transition($a,'in_progress','Employee saved appraisal draft.');$s->refresh($a->fresh());return back()->with('success','Appraisal draft saved.');}
 public function submitEmployee(Appraisal $a,AppraisalScoreService $s,AppraisalWorkflowService $w){abort_unless($this->employee($a),403);if($e=$s->weightErrors($a))return back()->with('error',implode(' ',$e));$a->update(['employee_submitted_at'=>now()]);$w->transition($a,'submitted','Submitted to assigned supervisor.');return back()->with('success','Submitted to your supervisor.');}
 public function saveSupervisor(Request $r,Appraisal $a,AppraisalScoreService $s,AppraisalWorkflowService $w){abort_unless($this->supervisor($a),403);$d=$r->validate(['manager_comments'=>'nullable|string|max:30000','development_plan'=>'nullable|string|max:30000','kras'=>'nullable|array','kras.*.supervisor_rating'=>'nullable|numeric|min:1|max:5','kras.*.agreed_rating'=>'nullable|numeric|min:1|max:5','kras.*.kpis'=>'nullable|array','kras.*.kpis.*.supervisor_score'=>'nullable|numeric|min:1|max:5','kras.*.kpis.*.agreed_score'=>'nullable|numeric|min:1|max:5']);$a->update(collect($d)->only(['manager_comments','development_plan'])->all());foreach(($d['kras']??[]) as $id=>$kd){$kra=AppraisalKra::where('appraisal_id',$a->id)->findOrFail($id);$kra->update(collect($kd)->only(['supervisor_rating','agreed_rating'])->all());foreach(($kd['kpis']??[]) as $kid=>$x)AppraisalKpi::where('appraisal_kra_id',$kra->id)->findOrFail($kid)->update($x);}if($a->status==='submitted')$w->transition($a,'supervisor_review','Supervisor started review.');$s->refresh($a->fresh());return back()->with('success','Supervisor review saved.');}
 public function reviewComplete(Appraisal $a,AppraisalWorkflowService $w){abort_unless($this->supervisor($a),403);$a->update(['manager_submitted_at'=>now()]);$w->transition($a,'meeting_pending','Supervisor review completed; meeting pending.');return back()->with('success','Review completed.');}
 public function meeting(Request $r,Appraisal $a,AppraisalWorkflowService $w){abort_unless($this->employee($a)||$this->supervisor($a),403);$d=$r->validate(['meeting_at'=>'required|date','venue'=>'nullable|string|max:255','participants'=>'nullable|string|max:5000','discussion_notes'=>'nullable|string|max:30000','disagreements'=>'nullable|string|max:30000','agreed_actions'=>'nullable|string|max:30000','development_commitments'=>'nullable|string|max:30000']);$d['recorded_by']=auth()->id();AppraisalMeeting::updateOrCreate(['appraisal_id'=>$a->id],$d);$a->update(['meeting_completed_at'=>now()]);$w->transition($a,'meeting_completed','Appraisal meeting recorded.');return back()->with('success','Meeting recorded.');}
 public function employeeConfirm(Request $r,Appraisal $a,AppraisalWorkflowService $w){abort_unless($this->employee($a),403);$a->update(['employee_final_comment'=>$r->input('comment'),'employee_confirmed_at'=>now()]);$w->transition($a,'supervisor_confirmation','Employee confirmed agreed appraisal.');return back()->with('success','Appraisal confirmed.');}
 public function supervisorConfirm(Request $r,Appraisal $a,AppraisalWorkflowService $w){abort_unless($this->supervisor($a),403);$a->update(['supervisor_final_comment'=>$r->input('comment'),'supervisor_confirmed_at'=>now()]);$w->transition($a,'completed','Supervisor confirmed appraisal.');return back()->with('success','Appraisal completed.');}
 private function authorise(Appraisal $a):void{abort_unless($this->employee($a)||$this->supervisor($a)||auth()->user()?->isSuperAdmin()||auth()->user()?->hasAnyRole(['hr','HR','administrator']),403);} private function employee(Appraisal $a):bool{return (int)$a->employee?->user_id===(int)auth()->id();} private function supervisor(Appraisal $a):bool{return (int)$a->manager_user_id===(int)auth()->id();}
}
