@extends('layouts.app')
@section('title','Course Opportunities | ElevateHer360')
@section('content')
<style>.eh-track-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:0 0 22px}.eh-track-card{background:#fff;border:1px solid #eadede;border-left:4px solid #800000;border-radius:12px;padding:16px;display:flex;align-items:center;gap:12px}.eh-track-card i{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:#fff7da;color:#800000}.eh-call-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.eh-call-card{display:block;background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px;color:inherit}.eh-call-card-footer{margin-top:14px;display:flex;justify-content:space-between;align-items:center}@media(max-width:900px){.eh-track-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.eh-call-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.eh-track-grid,.eh-call-grid{grid-template-columns:1fr}}</style>
<div class="page-header"><div><span class="eh-kicker">Learning</span><h1>Course Opportunities</h1><p>Apply for open WITU course opportunities and track your submissions.</p></div></div>
<div class="eh-track-grid"><div class="eh-track-card"><i class="fas fa-bullhorn"></i><div><small>Available Opportunities</small><strong>{{ number_format($stats['available']??0) }}</strong></div></div><div class="eh-track-card"><i class="fas fa-file-pen"></i><div><small>My Applications</small><strong>{{ number_format($stats['applications']??0) }}</strong></div></div><div class="eh-track-card"><i class="fas fa-magnifying-glass"></i><div><small>Under Review</small><strong>{{ number_format($stats['review']??0) }}</strong></div></div><div class="eh-track-card"><i class="fas fa-circle-check"></i><div><small>Accepted / Successful</small><strong>{{ number_format($stats['successful']??0) }}</strong></div></div></div>
@php $activeTab=request('tab')==='submissions'?'submissions':'available'; @endphp
<div class="eh-tabs"><div class="eh-tab-nav"><a class="eh-tab-link {{ $activeTab==='available'?'active':'' }}" href="{{ route('participant.course-calls.index') }}"><i class="fas fa-bullhorn"></i> Available</a><a class="eh-tab-link {{ $activeTab==='submissions'?'active':'' }}" href="{{ route('participant.course-calls.index',['tab'=>'submissions']) }}"><i class="fas fa-folder-open"></i> My Submissions</a></div><div class="eh-tab-content">
@if($activeTab==='available')<div class="eh-tab-section"><div class="eh-call-grid">@forelse($calls as $call)@php $my=$mine->get($call->id); @endphp<a class="eh-call-card" href="{{ route('participant.course-calls.show',$call) }}"><span class="eh-kicker">{{ $call->course?->title??'Course Opportunity' }}</span><h3>{{ $call->title }}</h3><p>{{ \Illuminate\Support\Str::limit(strip_tags($call->description),140) }}</p><small>Closes: {{ $call->closes_at?->format('d M Y H:i')??'Open until closed' }}</small><div class="eh-call-card-footer"><strong>{{ $my?ucwords(str_replace('_',' ',$my->status)):'Apply' }}</strong><i class="fas fa-chevron-right"></i></div></a>@empty<div class="eh-empty"><h3>No open course opportunities</h3></div>@endforelse</div>{{ $calls->appends(['tab'=>'available'])->links() }}</div>@else<div class="eh-tab-section"><div class="eh-data-list">@forelse($submissions as $application)<a class="eh-data-row" href="{{ route('participant.course-calls.show',$application->courseCall) }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-file-lines"></i></span><div class="eh-data-row-copy"><strong>{{ $application->courseCall?->title??'Course Application' }}</strong><span>@if($application->submitted_at)Submitted {{ $application->submitted_at->format('d M Y H:i') }}@else Draft application @endif @if($application->reviewer_comments) Â· Feedback available @endif</span></div></div><span class="eh-status">{{ $application->status }}</span></a>@empty<div class="eh-empty"><h3>No submissions yet</h3><p>Your course applications and drafts will appear here.</p></div>@endforelse</div>{{ $submissions->appends(['tab'=>'submissions'])->links() }}</div>@endif
</div></div>
@endsection