<div class="eh-modal" id="{{ $id }}" aria-hidden="true"><div class="eh-modal-dialog eh-modal-lg">
<div class="eh-modal-header"><div><h2>{{ $title }}</h2><p>Complete the cohort setup details.</p></div><button type="button" class="eh-modal-close" data-modal-close><i class="fas fa-xmark"></i></button></div>
<form method="POST" action="{{ $action }}">@csrf @if($method==='PUT') @method('PUT') @endif
<div class="eh-modal-body"><div class="modal-grid">
<div class="form-group full"><label>Name *</label><input name="name" value="{{ $cohort->name }}" placeholder="e.g. Kampala Cohort 1 - 2026" required><small class="form-hint">Required. Use a clear cohort name that participants and staff can recognise.</small></div>
<div class="form-group"><label>Code</label><input name="code" value="{{ $cohort->code }}" placeholder="e.g. KLA-C1-26"><small class="form-hint">Optional. Enter a unique short cohort code.</small></div>
<div class="form-group"><label>Status *</label><select name="status">@foreach(['planned','open','active','completed','cancelled'] as $s)<option value="{{ $s }}" @selected(($cohort->status ?: 'planned')===$s)>{{ ucfirst($s) }}</option>@endforeach</select><small class="form-hint">Required. Select the current cohort lifecycle status.</small></div>
<div class="form-group"><label>Programme</label><select name="programme_id"><option value="">None</option>@foreach($programmes as $p)<option value="{{ $p->id }}" @selected((string)$cohort->programme_id===(string)$p->id)>{{ $p->name }}</option>@endforeach</select><small class="form-hint">Optional. Link the cohort to its programme.</small></div>
<div class="form-group"><label>Project</label><select name="project_id"><option value="">None</option>@foreach($projects as $p)<option value="{{ $p->id }}" @selected((string)$cohort->project_id===(string)$p->id)>{{ $p->name }}</option>@endforeach</select><small class="form-hint">Optional. Link the cohort to a specific project.</small></div>
<div class="form-group"><label>Branch</label><select name="branch_id"><option value="">None</option>@foreach($branches as $b)<option value="{{ $b->id }}" @selected((string)$cohort->branch_id===(string)$b->id)>{{ $b->name }}</option>@endforeach</select><small class="form-hint">Optional. Select the delivery branch/location.</small></div>
<div class="form-group"><label>Start Date</label><input type="date" name="start_date" value="{{ optional($cohort->start_date)->format('Y-m-d') }}"><small class="form-hint">Optional. Choose the cohort start date.</small></div>
<div class="form-group"><label>End Date</label><input type="date" name="end_date" value="{{ optional($cohort->end_date)->format('Y-m-d') }}"><small class="form-hint">Optional. Must be on or after the start date.</small></div>
</div></div><div class="eh-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Cancel</button><button class="btn btn-primary">{{ $method==='POST' ? 'Create Cohort':'Save Changes' }}</button></div>
</form></div></div>