@extends(auth()->check() && method_exists(auth()->user(), 'isStaff') && auth()->user()->isStaff() ? 'layouts.admin' : 'layouts.app')
@section('title','My Applications - ElevateHer360')
@section('content')
<style>.eh-track-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:0 0 22px}.eh-track-card{background:#fff;border:1px solid #eadede;border-left:4px solid #800000;border-radius:12px;padding:16px;display:flex;align-items:center;gap:12px}.eh-track-card i{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:#fff7da;color:#800000}.eh-track-card small{display:block;color:#667085;font-weight:700}.eh-track-card strong{font-size:1.3rem;color:#101828}@media(max-width:900px){.eh-track-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.eh-track-grid{grid-template-columns:1fr}}.eh-data-row{flex-wrap:wrap}.eh-app-timeline{flex-basis:100%;display:flex;align-items:center;flex-wrap:wrap;gap:6px;margin-top:10px;font-size:.78rem;color:#667085}.eh-app-step{background:#f4f1ee;border:1px solid #eadede;border-radius:20px;padding:2px 10px}.eh-app-timeline i{font-size:.6rem;color:#c4a0a0}</style>
<div class="page-header"><div><span class="eh-kicker">Opportunities</span><h1>My Job Applications</h1><p>Track your submitted job applications and their current status.</p></div><x-export-buttons /></div>
<div class="eh-track-grid"><div class="eh-track-card"><i class="fas fa-folder-open"></i><div><small>Total Applications</small><strong>{{ number_format($stats['total']??0) }}</strong></div></div><div class="eh-track-card"><i class="fas fa-magnifying-glass"></i><div><small>Submitted / Under Review</small><strong>{{ number_format($stats['review']??0) }}</strong></div></div><div class="eh-track-card"><i class="fas fa-user-check"></i><div><small>Shortlisted / Interview</small><strong>{{ number_format($stats['shortlisted']??0) }}</strong></div></div><div class="eh-track-card"><i class="fas fa-trophy"></i><div><small>Successful / Offered</small><strong>{{ number_format($stats['successful']??0) }}</strong></div></div></div>
<div class="eh-tabs"><div class="eh-tab-nav"><a class="eh-tab-link" href="{{ route('jobs.index') }}"><i class="fas fa-briefcase"></i> Opportunities</a><a class="eh-tab-link active" href="{{ route('jobs.applications') }}"><i class="fas fa-folder-open"></i> My Applications</a></div><div class="eh-tab-content"><div class="eh-tab-section"><div class="eh-data-list">@forelse($applications as $application)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-paper-plane"></i></span><div class="eh-data-row-copy"><strong>{{ $application->job?->title??'Job Opportunity' }}</strong><span>{{ $application->job?->employer?->company_name??'Employer' }} @if($application->applied_at) Ã‚Â· Applied {{ $application->applied_at->format('d M Y') }} @endif</span></div></div><span class="eh-status">{{ $application->status }}</span></div>@if($application->statusHistory->isNotEmpty())<div class="eh-app-timeline">{{ $application->statusHistory->pluck('status')->map(fn ($s) => ucfirst(str_replace('_', ' ', $s)))->join(' → ') }}</div>@endif
@empty<div class="eh-empty"><i class="fas fa-folder-open"></i><h3>No applications yet</h3><p>Browse available opportunities and submit your first application.</p><a class="btn btn-primary" href="{{ route('jobs.index') }}">Browse Jobs</a></div>@endforelse</div>{{ $applications->links() }}</div></div></div>
@endsection
