<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
class ExpandAppraisalWorkflowReporting extends Migration {
 public function up(): void {
  if(Schema::hasTable('appraisals')){
   if(DB::getDriverName()==='mysql') DB::statement("ALTER TABLE appraisals MODIFY status VARCHAR(50) NOT NULL DEFAULT 'draft'");
   Schema::table('appraisals',function(Blueprint $t){
    foreach(['achievements','challenges','support_required','learning_completed','development_needs','employee_final_comment','supervisor_final_comment','reopened_reason'] as $c) if(!Schema::hasColumn('appraisals',$c)) $t->longText($c)->nullable();
    foreach(['meeting_completed_at','employee_confirmed_at','supervisor_confirmed_at','locked_at','reopened_at'] as $c) if(!Schema::hasColumn('appraisals',$c)) $t->timestamp($c)->nullable();
   });
  }
  if(!Schema::hasTable('staff_supervisor_assignments')) Schema::create('staff_supervisor_assignments',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('supervisor_user_id')->constrained('users')->cascadeOnDelete();$t->date('effective_from')->nullable();$t->date('effective_to')->nullable();$t->boolean('is_active')->default(true);$t->foreignId('assigned_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  if(!Schema::hasTable('appraisal_kras')) Schema::create('appraisal_kras',function(Blueprint $t){$t->id();$t->foreignId('appraisal_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->text('expected_result')->nullable();$t->text('actual_result')->nullable();$t->decimal('weight',5,2)->default(0);$t->decimal('employee_rating',5,2)->nullable();$t->decimal('supervisor_rating',5,2)->nullable();$t->decimal('agreed_rating',5,2)->nullable();$t->text('employee_comment')->nullable();$t->text('supervisor_comment')->nullable();$t->unsignedInteger('position')->default(0);$t->timestamps();});
  if(!Schema::hasTable('appraisal_kpis')) Schema::create('appraisal_kpis',function(Blueprint $t){$t->id();$t->foreignId('appraisal_kra_id')->constrained('appraisal_kras')->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('measurement_method')->nullable();$t->string('target')->nullable();$t->string('actual_achievement')->nullable();$t->string('unit')->nullable();$t->string('kpi_type')->default('qualitative');$t->decimal('weight',5,2)->default(0);$t->decimal('employee_score',5,2)->nullable();$t->decimal('supervisor_score',5,2)->nullable();$t->decimal('agreed_score',5,2)->nullable();$t->text('evidence')->nullable();$t->text('employee_comment')->nullable();$t->text('supervisor_comment')->nullable();$t->unsignedInteger('position')->default(0);$t->timestamps();});
  if(!Schema::hasTable('appraisal_competencies')) Schema::create('appraisal_competencies',function(Blueprint $t){$t->id();$t->foreignId('appraisal_id')->constrained()->cascadeOnDelete();$t->string('name');$t->decimal('weight',5,2)->default(0);$t->decimal('employee_rating',5,2)->nullable();$t->decimal('supervisor_rating',5,2)->nullable();$t->decimal('agreed_rating',5,2)->nullable();$t->text('employee_comment')->nullable();$t->text('supervisor_comment')->nullable();$t->timestamps();});
  if(!Schema::hasTable('appraisal_meetings')) Schema::create('appraisal_meetings',function(Blueprint $t){$t->id();$t->foreignId('appraisal_id')->unique()->constrained()->cascadeOnDelete();$t->dateTime('meeting_at')->nullable();$t->string('venue')->nullable();$t->text('participants')->nullable();$t->longText('discussion_notes')->nullable();$t->longText('disagreements')->nullable();$t->longText('agreed_actions')->nullable();$t->longText('development_commitments')->nullable();$t->text('employee_comments')->nullable();$t->text('supervisor_comments')->nullable();$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  if(!Schema::hasTable('appraisal_status_history')) Schema::create('appraisal_status_history',function(Blueprint $t){$t->id();$t->foreignId('appraisal_id')->constrained()->cascadeOnDelete();$t->string('from_status')->nullable();$t->string('to_status');$t->text('comment')->nullable();$t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();$t->string('ip_address',45)->nullable();$t->timestamps();});
  if(!Schema::hasTable('data_imports')) Schema::create('data_imports',function(Blueprint $t){$t->id();$t->string('module');$t->string('original_filename');$t->string('stored_path')->nullable();$t->json('column_mapping')->nullable();$t->unsignedInteger('total_rows')->default(0);$t->unsignedInteger('valid_rows')->default(0);$t->unsignedInteger('invalid_rows')->default(0);$t->unsignedInteger('imported_rows')->default(0);$t->string('status')->default('uploaded');$t->json('errors')->nullable();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('confirmed_at')->nullable();$t->timestamps();});
  if(!Schema::hasTable('job_tracking_events')) Schema::create('job_tracking_events',function(Blueprint $t){$t->id();$t->unsignedBigInteger('user_id');$t->unsignedBigInteger('job_id')->nullable();$t->unsignedBigInteger('job_application_id')->nullable();$t->string('event_type');$t->string('employer')->nullable();$t->string('position')->nullable();$t->date('event_date')->nullable();$t->text('notes')->nullable();$t->json('metadata')->nullable();$t->foreignId('recorded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['user_id','event_type']);});
 }
 public function down(): void {foreach(['job_tracking_events','data_imports','appraisal_status_history','appraisal_meetings','appraisal_competencies','appraisal_kpis','appraisal_kras','staff_supervisor_assignments'] as $t) Schema::dropIfExists($t);}
}
