@extends('layouts.admin')
@section('title','Branches | ElevateHer360 Administration')
@section('content')
<div class="admin-page-header"><div><span class="admin-eyebrow">Programme Management</span><h1>Branches</h1><p>Manage programme delivery locations and branch status.</p></div><div class="admin-page-actions"><button type="button" class="btn btn-primary" data-modal-open="branchCreate"><i class="fas fa-plus"></i> Add Branch</button></div></div>
@include('admin.shared.feedback')
<div class="admin-stats-grid compact">@foreach([['total','Total Branches','fa-building'],['active','Active','fa-circle-check'],['inactive','Inactive','fa-circle-pause'],['districts','Districts','fa-location-dot']] as [$k,$l,$i])<div class="admin-stat"><span class="admin-stat-icon"><i class="fas {{ $i }}"></i></span><div><small>{{ $l }}</small><strong>{{ number_format($stats[$k]??0) }}</strong></div></div>@endforeach</div>
<div class="admin-panel"><form method="GET" class="admin-toolbar"><div class="search-box"><i class="fas fa-magnifying-glass"></i><input name="search" value="{{ request('search') }}" placeholder="Search branch, code, district or country..."></div><select name="status"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><select name="per_page">@foreach([10,20,25,50,100] as $n)<option value="{{ $n }}" @selected((int)request('per_page',20)===$n)>{{ $n }}/page</option>@endforeach</select><button class="btn btn-primary btn-sm">Apply</button><a href="{{ route('admin.branches.index') }}" class="btn btn-outline btn-sm">Reset</a></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Branch</th><th>District</th><th>Country</th><th>Status</th><th class="table-actions">Actions</th></tr></thead><tbody>@forelse($branches as $branch)<tr><td><strong>{{ $branch->name }}</strong><small class="admin-cell-hint">{{ $branch->code ?: 'No code' }}</small></td><td>{{ $branch->district ?: '—' }}</td><td>{{ $branch->country }}</td><td><span class="status-chip {{ $branch->is_active ? 'active':'inactive' }}">{{ $branch->is_active ? 'Active':'Inactive' }}</span></td><td class="table-actions"><div class="action-group"><button class="btn-icon" type="button" data-modal-open="branch{{ $branch->id }}"><i class="fas fa-pen"></i></button><button class="btn-icon danger" type="button" data-modal-open="branchDelete{{ $branch->id }}"><i class="fas fa-trash"></i></button></div></td></tr>@empty<tr><td colspan="5"><div class="admin-empty">No branches found.</div></td></tr>@endforelse</tbody></table></div><div class="admin-pagination">{{ $branches->links() }}</div></div>
@php($blank=new \App\Models\Branch(['country'=>'Uganda','is_active'=>true]))
@include('admin.branches.modal',['id'=>'branchCreate','title'=>'Add Branch','branch'=>$blank,'action'=>route('admin.branches.store'),'method'=>'POST'])
@foreach($branches as $branch)
@include('admin.branches.modal',['id'=>'branch'.$branch->id,'title'=>'Edit Branch','branch'=>$branch,'action'=>route('admin.branches.update',$branch),'method'=>'PUT'])
<div class="eh-modal" id="branchDelete{{ $branch->id }}" aria-hidden="true"><div class="eh-modal-dialog eh-modal-sm"><div class="eh-modal-header"><div><h2>Delete Branch?</h2><p>{{ $branch->name }}</p></div><button type="button" class="eh-modal-close" data-modal-close><i class="fas fa-xmark"></i></button></div><div class="eh-modal-body"><p>Delete only when no dependent records use this branch.</p></div><div class="eh-modal-footer"><button type="button" class="btn btn-outline" data-modal-close>Cancel</button><form method="POST" action="{{ route('admin.branches.destroy',$branch) }}">@csrf @method('DELETE')<button class="btn btn-danger">Delete</button></form></div></div></div>
@endforeach
@endsection
