@extends('layouts.app')
@section('title','My Learning - ElevateHer360')
@section('content')
<div class="page-header"><div><span class="eh-kicker">Learning</span><h1>My Learning</h1><p>Continue enrolled courses and review your progress.</p></div><a href="{{ route('learning.index') }}" class="btn btn-outline"><i class="fas fa-magnifying-glass"></i> Browse Courses</a></div>
<div class="eh-tabs" data-eh-tabs>
<div class="eh-tab-nav" role="tablist"><button class="eh-tab-button active" data-eh-tab="courses" aria-selected="true"><i class="fas fa-graduation-cap"></i> My Courses</button><button class="eh-tab-button" data-eh-tab="progress" aria-selected="false"><i class="fas fa-chart-line"></i> Progress</button></div>
<div class="eh-tab-content">
<section class="eh-tab-pane active" data-eh-pane="courses"><div class="eh-tab-section"><div class="eh-data-list">@forelse($enrolments as $enrolment)<a class="eh-data-row" href="{{ route('learning.course.show',$enrolment->course) }}"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-book-open"></i></span><div class="eh-data-row-copy"><strong>{{ $enrolment->course->title }}</strong><span>Status: {{ ucfirst(str_replace('_',' ',$enrolment->status)) }} · {{ $enrolment->progress_percent ?? 0 }}% complete</span></div></div><div class="eh-data-row-actions"><span class="eh-status">{{ $enrolment->status }}</span><i class="fas fa-chevron-right"></i></div></a>@empty<div class="eh-empty"><i class="fas fa-graduation-cap"></i><h3>No courses yet</h3><p>Browse available courses and start learning.</p><a class="btn btn-primary" href="{{ route('learning.index') }}">Browse Courses</a></div>@endforelse</div>{{ $enrolments->links() }}</div></section>
<section class="eh-tab-pane" data-eh-pane="progress"><div class="eh-tab-section"><div class="eh-tab-section-header"><div><h2>Course Progress</h2><p>A simple view of progress across your enrolments.</p></div></div><div class="eh-data-list">@forelse($enrolments as $enrolment)<div class="eh-data-row"><div class="eh-data-row-main"><span class="eh-data-row-icon"><i class="fas fa-chart-simple"></i></span><div class="eh-data-row-copy"><strong>{{ $enrolment->course->title }}</strong><span>{{ $enrolment->progress_percent ?? 0 }}% complete</span></div></div><strong>{{ $enrolment->progress_percent ?? 0 }}%</strong></div>@empty<div class="eh-empty"><p>No learning progress to display yet.</p></div>@endforelse</div></div></section>
</div></div>
@endsection
